support async function for readFileFn
flowjs/flow.js pull request #304
Opened 2020-07-30 03:41 UTC by drzraf

See #296 and #300

2020-07-30 06:40 UTC, AidasK commented
Can you also check that async is compiled in dist/ folder to ES5 via grunt? This way you could use promises everywhere. Though you might need to update examples and docs due to a breaking changes

2020-07-30 14:24 UTC, drzraf commented
- Not sure I understood. I commited the result of `grunt template` too. What else?
- The update to `karma-coverage` (needed for `async` support does not seem to play well with the rest of Travis [but the testsuite is green on my local system. Any hint?

2020-07-31 06:36 UTC, AidasK commented
The thing is that grunt does not compile files to es5, that means that browsers are going to crash if they do not support `async` syntax. That is why we need to update grunt minify method to recompile file to es5.

2020-08-29 09:14 UTC, AidasK commented
Is this ready to be merged?

2020-09-03 21:35 UTC, drzraf commented
No, I'm revamping the PR because the way I checked for asynchronicity of function is not compatible with bundled code.
(I'll provide a test too).
https://github.com/flowjs/flow.js/pull/309 is a prerequisite as this brings in a transpilation toolchain and testing transpiled code instead of sourcecode.

2020-09-12 12:59 UTC, AidasK requested changes

2020-09-12 12:59 UTC, AidasK commented on src/flow.js
> +    },
1. read_guard should be renamed to readGuard for consistency. 
2. console.log has to go
3. await sleep(100) dictates poor design. Instead it should be promise based. Since we are releasing v3 version, readStates can be removed.

2020-09-12 12:59 UTC, AidasK commented on test/asyncSpec.js
> +  it('synchronous initFileFn and asyncReadFileFn', async function (done) {
travis build does not pass 1 test

2020-09-14 21:41 UTC, drzraf commented
Note: I observed problems with progress reporting using `test/FakeXMLHttpRequestUpload.js` (see https://github.com/flowjs/flow.js/pull/313)

2020-09-15 14:32 UTC, drzraf commented on test/asyncSpec.js
> +  it('synchronous initFileFn and asyncReadFileFn', async function (done) {
I don't get why.
It's probably an error parsing the JS code of the test, but what exactly? (https://caniuse.com/?compare=firefox+60,firefox+80&compareCats=JS):
- backticks
- async
- window.crypto.subtle.digest
- Uint8Array
- TextEncoder

I guess all of these are supported by FF 60...

2020-09-15 15:36 UTC, drzraf commented on test/asyncSpec.js
> +  it('synchronous initFileFn and asyncReadFileFn', async function (done) {
I tried SauceLabs locally, but get errors:
```
15 09 2020 12:31:46.912:INFO [launcher]: Starting browser firefox 45 (Linux) on SauceLabs
2020-09-15T15:32:43.192Z ERROR webdriver: Request failed with status 500 due to Error: Infrastructure Error -- The Sauce VMs failed to start the browser or device.
For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
2020-09-15T15:32:43.196Z ERROR webdriver: Error: Infrastructure Error -- The Sauce VMs failed to start the browser or device.
For more info, please check https://wiki.saucelabs.com/display/DOCS/Common+Error+Messages
    at getErrorFromResponseBody (flow.js/node_modules/webdriver/build/utils.js:121:10)
    at WebDriverRequest._request (/flow.js/node_modules/webdriver/build/request.js:149:56)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

2020-09-16 07:37 UTC, AidasK commented on src/flow.js
> +      this.readState = 2;
Since we are releasing v3 version, maybe it's simpler to make some breaking changes? We can get rid off all those semaphores :))

2020-09-16 07:38 UTC, AidasK commented on src/flow.js
> +    XhrSend: function (bytes) {
XhrSend should be lowercased to `xhrSend` for consistency

2020-09-16 07:42 UTC, AidasK commented on test/asyncSpec.js
> +  it('synchronous initFileFn and asyncReadFileFn', async function (done) {
Have you tried running it on the latest firefox? If it works, it might be just a quirk on saucelabs

2020-09-16 14:12 UTC, drzraf commented on src/flow.js
> +      this.readState = 2;
I agree Deferred-based locking could benefit to the rest of the codebase, but could we postpone that to a later commit, otherwise this will significantly broaden the scope of the PR and make it harder to review/test/revert.

2020-09-16 14:24 UTC, drzraf commented on test/asyncSpec.js
> +  it('synchronous initFileFn and asyncReadFileFn', async function (done) {
`karma start karma.conf.js --browsers=sl_firefox_2` (actually modified it for FF45)

```
16 09 2020 11:22:33.219:DEBUG [launcher.SauceConnect]: 16 Sep 11:22:33 - Sauce Connect is up, you may start your tests.
16 09 2020 11:23:09.815:WARN [launcher]: firefox 45 (Linux) on SauceLabs have not captured in 60000 ms, killing.
16 09 2020 11:23:09.816:ERROR [SaucelabsLauncher]: Could not quit the Saucelabs selenium connection. Failure message:
16 09 2020 11:23:09.816:ERROR [SaucelabsLauncher]: TypeError: Cannot read property 'deleteSession' of null
```

I don't know what am I doing wrong.

2020-09-16 15:58 UTC, drzraf commented on test/asyncSpec.js
> +  it('synchronous initFileFn and asyncReadFileFn', async function (done) {
I think the issue is related to https://github.com/karma-runner/karma-sauce-launcher/issues/210
Could you please investigate whether SauceLabs backend is correctly configured?

2020-09-16 17:37 UTC, drzraf commented
Added more tests about chunk size mismatch.
I ran a couple of `random` tests, all succeeded.
```
Test File is 36 bytes long. Now uploads 18 simultaneous chunks of at most 7 bytes
Test File is 31 bytes long. Now uploads 6 simultaneous chunks of at most 8 bytes
Test File is 7 bytes long. Now uploads 15 simultaneous chunks of at most 11 bytes
Test File is 66 bytes long. Now uploads 19 simultaneous chunks of at most 16 bytes
Test File is 29 bytes long. Now uploads 16 simultaneous chunks of at most 13 bytes
Test File is 84 bytes long. Now uploads 14 simultaneous chunks of at most 2 bytes
Test File is 49 bytes long. Now uploads 2 simultaneous chunks of at most 24 bytes
Test File is 24 bytes long. Now uploads 20 simultaneous chunks of at most 7 bytes
Test File is 41 bytes long. Now uploads 13 simultaneous chunks of at most 28 bytes
Test File is 17 bytes long. Now uploads 17 simultaneous chunks of at most 5 bytes
Test File is 21 bytes long. Now uploads 11 simultaneous chunks of at most 2 bytes
Test File is 16 bytes long. Now uploads 15 simultaneous chunks of at most 3 bytes
Test File is 67 bytes long. Now uploads 15 simultaneous chunks of at most 24 bytes
Test File is 65 bytes long. Now uploads 6 simultaneous chunks of at most 10 bytes
Test File is 14 bytes long. Now uploads 14 simultaneous chunks of at most 2 bytes
Test File is 83 bytes long. Now uploads 18 simultaneous chunks of at most 10 bytes
Test File is 76 bytes long. Now uploads 1 simultaneous chunks of at most 3 bytes
Test File is 2 bytes long. Now uploads 11 simultaneous chunks of at most 4 bytes
Test File is 34 bytes long. Now uploads 5 simultaneous chunks of at most 2 bytes
Test File is 87 bytes long. Now uploads 15 simultaneous chunks of at most 8 bytes
Test File is 16 bytes long. Now uploads 9 simultaneous chunks of at most 2 bytes
Test File is 23 bytes long. Now uploads 13 simultaneous chunks of at most 5 bytes
Test File is 91 bytes long. Now uploads 1 simultaneous chunks of at most 5 bytes
Test File is 69 bytes long. Now uploads 11 simultaneous chunks of at most 4 bytes
Test File is 40 bytes long. Now uploads 1 simultaneous chunks of at most 6 bytes
Test File is 54 bytes long. Now uploads 6 simultaneous chunks of at most 9 bytes
Test File is 31 bytes long. Now uploads 8 simultaneous chunks of at most 13 bytes
Test File is 15 bytes long. Now uploads 2 simultaneous chunks of at most 1 bytes
Test File is 42 bytes long. Now uploads 10 simultaneous chunks of at most 11 bytes
Test File is 40 bytes long. Now uploads 1 simultaneous chunks of at most 25 bytes
```

2020-10-07 15:07 UTC, drzraf commented on test/asyncSpec.js
> +  it('synchronous initFileFn and asyncReadFileFn', async function (done) {
Doing:
`SAUCE_USERNAME=flowjs SAUCE_ACCESS_KEY=53e609a9-cb5d-4eac-a888-xxx grunt karma:saucelabs`
I still can't test saucelabs and can't explain why the CI fails.

I know how annoying to get an always-red CI and would prefer to avoid this.
Any hope you could take the time to double check the SauceLabs configuration? (and the travis' one?)

2020-10-15 22:21 UTC, drzraf commented
Closing in favor of #321

2020-10-15 22:21 UTC, closed without merging

2020-10-15 22:21 UTC, drzraf commented on test/asyncSpec.js
> +  it('synchronous initFileFn and asyncReadFileFn', async function (done) {
Did you stopped the CI ?